Fix bug in .run_freq_response().
* Fix a bug that happens when calling run_freq_response() with default arguments:
AttributeError: 'NoneType' object has no attribute 'imag'
* Since running .run_modal() is required to create the attribute "evalues", we need to call this function (run_modal()) before creating a 
default speed_range based on the evalues.